name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 16.x
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm
    run: |
      npm install
      npm run lint:js
      npm run lint:css
      npm run build
      npm run analyze 
      npm run validate
  merge:  
    runs-on: ubuntu-latest
    steps:  
      - if: github.event_name = “pull_request”
        run: echo "123"